server:
  port: 8602
  spring:
  application:
    name: configService    # 对应config server所获取的配置文件的{application}
  cloud:
    config:
      uri: http://localhost:8601/
      profile: dev            # profile对应config server所获取的配置文件中的{profile} 
      label: master           # 指
            