server:
  port: 8766
spring:
  application:
    name: eureka_client_product2
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/