server:
  port: 8762
spring:
  application:
    name: eureka2
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8761/eureka