server:
  port: 8761
spring:
  application:
    name: eureka1
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8761/eureka
