server:
  port: 8601
spring:
  application:
    name: configService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2015Y/configFiles      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码