server:
  port: 8771
spring:
  application:
    name: zuul1
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
logging:
  level:
    com.netflix: DEBUG
