server:
  port: 8762
spring:
  application:
    name: discovery2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka